### PR TITLE
Add nginx http_stub_status_module module

### PR DESCRIPTION
**Pull request by ghantoos**
This commit adds the compilation flag `--with-http_stub_status_module` to nginx, which adds the possibility to get stats from an nginx status page.

### CODE REVIEW

**Comment by sportebois** [comment]
Why did these bin were there? I don't have memory about that :( (I assume this is cleaner, but I don't have time to dig right now so it' easier to ask ;-)

**Comment by ghantoos** [comment]
Those are the binaries that are downloaded and used in the buildpack. Generated using `make`. You updated them in your last PR, so I did the same thing :)

image

**Comment by sportebois** [comment]
One of the cases we're glad to have git to not have to remember these details in our head ;-)

**Review by sportebois — APPROVED** [review]
👌 , but before merging these, could you let us know when the same code is deployed on staging from [your  fork](https://github.com/ghantoos/nginx-buildpack), I'd love to see the real results of this + the nginx config update on staging.

**Review by lussier — APPROVED** [review]

**Review by alavers — APPROVED** [review]
LGTM

**Comment by alavers** [comment]
I think I just answered my own question by looking at https://github.com/smooch/smooch/pull/3210

**Pull request merged**
